sudo: required
services:
    - docker

before_install:
    - docker build -t stevenu/docker-react -f dockerfile.dev .

script:
    - docker run -e CI=true stevenu/docker-react npm run test

language: 
    - generic 