sudo: required
services:
    - docker

before_install:
    - docker build -t stevenu/docker-react -f dockerfile.dev .

script:
    - docker run -e CI=true stevenu/docker-react npm run test

language: 
    - generic 

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "Docker_react"
    envoirnment: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-1-216384975593"
    bucket_path: "Docker_react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY




